name: CI/CD Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [published] # Upon every Release，the CD pipeline should run and automagically update

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python -m pytest tests/

  deploy:
    needs: test # This ensures deploy only runs if tests pass
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_HOST }} << 'EOF'
            cd ${{ secrets.EC2_PROJECT_PATH }}
            git pull origin main
            source venv/bin/activate
            pkill -f "uvicorn" || true
            nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 > out.log 2>&1 &
          EOF

      # - name: Build Docker image
      #   run: docker build -t common-assessment-tool .

      # - name: Run Docker container
      #   run: |
      #     docker run -d -p 8000:8000 common-assessment-tool
      #     sleep 10  # Wait for container to start

      # - name: Test Docker container
      #   run: |
      #     curl http://localhost:8000/docs
