name: Python CI Pipeline

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  test:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Checkout the repository

      - name: Set up Python
        uses: actions/setup-python@v5 # Set up Python environment
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version
          pip install setuptools wheel
          pip install -r requirements.txt  # Install dependencies from requirements.txt
          pip install pylint pytest
          pip install black


      - name: Run Tests
        run: |
          python -m pytest tests/

      - name: Run Pylint
        run: |
          pylint app/

      - name: Check code formatting with Black
        run: |
          black --check .

      - name: Format code with Black
        run: |
          black .
        
      - name: Build Docker Image (syntax check)
        run: |
          docker build -t my-app:test .
      
      - name: Run Docker Container
        run: |
          docker run --rm -d --name test-container -p 8000:8000 my-app:test
          sleep 5  # Give it time to start
          docker ps  # Verify it's running

      - name: Print Success Message
        run: |
          echo "CI Pipeline completed successfully!"
          echo "========================"
          echo "✓ Code checked out"
          echo "✓ Python environment set up"
          echo "✓ Dependencies installed"
          echo "✓ Tests executed"
          echo "✓ Linting completed"
          echo "========================"
